
# The below are highly dependent on trim
center_of_buoyancy = [0.00012155, -0.000034256, -0.00089525]
buoyancy_force = 190.0 # green: 215, black: 187 FUDGED to assume postively buoyant sub
gravity_force = 189.38

# only used for partially submerged buoyancy force calculation, non critical
sub_height = 0.50

# distance from dvl beam to axis of rotation used to offset velocity
# to account for misaligned reference point and dvl position
# for minisub, probably doesn't matter
dvl_offset = 0.0

# Moments of inertia (kg * m^2) from solidworks.
# In the model frame.
I = [[ 0.6149, -0.0054, -0.0662],
     [-0.0054,  0.7710, -0.0084],
     [-0.0662, -0.0084,  1.0121]]

# Ib and body_rot calculated using auv-body-frame-calc.
Ib = [0.60389, 0.771048, 1.02306]
# A normalized quaternion representing rotation from the body to the model frame.
btom_rq = [-0.0211005, -0.0803856, -0.0130816, 0.996455]
cwhe_axes = [69.35220358000004, 69.35220358, 106.68669116000001, 23.593943234140003, 27.380105203528004, 36.58328738845]
thruster_minimums = [-64.54730606800004, -64.547306068, -112.09220086100001, -23.742895057012003, -27.504311804213202, -36.561665349646006]
thruster_maximums = [74.15710109200003, 74.15710109199999, 101.28118145900001, 23.444991411268003, 27.2558986028428, 36.604909427254]

quaternion_filtering = 1
dvl_present = false
gx_hpr = [0.0, 0.0, 0.0] # Note: You probably want to re-tare the GX rather than use this offset


[[thrusters]]
name = "fore_port"
type = "T200"
pos = [0.235, -0.201, -0.0204]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "port"
type = "T200"
pos = [0.00474, -0.252, -0.0056]
heading_pitch = [0.0, 0.0]
reversed = false

[[thrusters]]
name = "aft_port"
type = "T200"
pos = [-0.271, -0.201, -0.0204]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "sway_aft"
type = "T200"
pos = [-0.271, -0.006, 0.031]
heading_pitch = [90.0, 0.0]
reversed = false

[[thrusters]]
name = "aft_starboard"
type = "T200"
pos = [-0.271, 0.201, -0.0204]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "starboard"
type = "T200"
pos = [0.00474, 0.252, -0.0056]
heading_pitch = [0.0, 0.0]
reversed = false

[[thrusters]]
name = "fore_starboard"
type = "T200"
pos = [0.235,  0.201, -0.0204]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "sway_fore"
type = "T200"
pos = [0.280, -0.006, 0.031]
heading_pitch = [90.0, 0.0]
reversed = false


[control_settings]
depth   = { kP = 7.00, kI = 0.15, kD = 15.00, rD = 0.3, ramp_speed = 0.5 }
pitch   = { kP = 0.10, kI = 0.10, kD = 11.00, rD = 30.0 }
heading = { kP = 0.40, kI = 0.00, kD = 18.00, rD = 20.0 }
velx    = { kP = 5.00, kI = 0.00, kD = 0.00, rD = 0.1547 }
vely    = { kP = 5.00, kI = 0.00, kD = 0.00, rD = 0.5 }
roll    = { kP = 0.14, kI = 0.01, kD = 10.00, rD = 30.0 }
quat    = { kP = 30.0, kI = 0.00, kD = 4.00 }


# horizontal, produces drag when diving and pitching
[[drag_planes]]
pos = [0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.0

[[drag_planes]]
pos = [-1.0, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.0

# fore sway, produces drag when swaying and rolling
[[drag_planes]]
pos = [0.0, 0.0, -0.10]
normal = [0.0, 1.0, 0.0]
cD = 2.0
area = 0.0

# aft sway
[[drag_planes]]
pos = [0.0, 0.0, 0.10]
normal = [0.0, 1.0, 0.0]
cD = 2.0
area = 0.0

# vertical, produces drag when going forward and yawing
[[drag_planes]]
pos = [0.0, -0.25, 0.0]
normal = [1.0, 0.0, 0.0]
cD = 2.0
area = 0.0

[[drag_planes]]
pos = [0.0, 0.25, 0.0]
normal = [1.0, 0.0, 0.0]
cD = 2.0
area = 0.0


# horizontal, produces drag when diving and pitching
[[uncompensated_drag_planes]]
pos = [0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.0

[[uncompensated_drag_planes]]
pos = [-0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.0


[sensors]
depth = "depth.depth"
depth_offset = "depth.offset_minisub"
heading_rate = "gx4.ratez"
pitch_rate = "gx4.ratey"
roll_rate = "gx4.ratex"
quaternion = "gx4"

[measurement_error]
velSigma = 0.005
depthSigma = 1.0
accSigma = 1000.0

[components]
port_forecam = [0.0, 0.0, 0.0]
starboard_forecam = [0.0, 0.0, 0.0]
downcam = [0.0, 0.0, 0.0]
sonar = [0.0, 0.0, 0.0]


[cameras.forward]
type = "ueye"
id = 3
camera_name = "ueye_forward_ajax" # for configuration
width = 1280
height = 1024
position = [0.48, 0.15, -0.08]
orientation_hpr = [0.0, 0.0, 0.0]

# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [7.2, 5.4]
# The focal length of the LENS in mm
focal_length_mm = 3.6

[cameras.downward]
type = "ueye"
id = 4
camera_name = "ueye_downward_ajax" # for configuration
width = 1024
height = 768
rotate180 = false
position = [0.0, 0.0, 0.15]
orientation_hpr = [0.0, -90.0, 0.0]

# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [4.76, 3.57]
focal_length_mm = 3.5


[vision_modules.gate]
capture_sources = ["forward"]

[vision_modules.vamp_buoy]
capture_sources = ["forward"]

[vision_modules.bins_cover]
capture_sources = ["downward"]

[vision_modules.bins_lever]
capture_sources = ["downward"]

[vision_modules.record]
capture_sources = ["forward", "downward"]

[vision_modules.poster]
capture_sources = ["forward", "downward"]

[vision_modules.calibrate]
capture_sources = ["default"]


[actuators]
left_marker = 2
right_marker = 2
