
# The below are highly dependent on trim
center_of_buoyancy = [-0.0005, -0.0025, -0.001]
buoyancy_force = 342.5 # green: 342.5, black: 330 FUDGED to assume postively buoyant sub
gravity_force = 314.809539

# only used for partially submerged buoyancy force calculation, non critical
sub_height = 0.50

# distance from dvl beam to axis of rotation used to offset velocity
# to account for misaligned reference point and dvl position
# for minisub, probably doesn't matter
dvl_offset = -0.2286

# Moments of inertia (kg * m^2) from solidworks.
# In the model frame.
I = [[ 0.7570, -0.0193, -0.0157],
     [-0.0193,  1.9297, -0.0038],
     [-0.0157, -0.0038,  2.0260]]

# Ib and body_rot calculated using auv-body-frame-calc.
Ib = [0.756487, 1.92989, 2.02633]
# A normalized quaternion representing rotation from the body to the model frame.
btom_rq = [0.999321, 0.0368397, 0.000307939, 0.000223085]
cwhe_axes = [69.35220358000004, 69.35220358, 106.68669116000001, 24.493862265233396, 33.82699177560289, 50.700275188176896]
thruster_minimums = [-64.547306068, -64.547306068, -112.092200861, -24.3638793369, -33.5977377427, -50.2038399041]
thruster_maximums = [74.15710109200003, 74.15710109199999, 101.28118145900001, 24.623845193585087, 34.056245808511505, 51.196710472260214]

quaternion_filtering = 1
dvl_present = true
use_dvl_for_depth = false
water_depth = 4.2672
gx_hpr = [0.0, 64.0, 15.0] # Note: You probably want to re-tare the GX rather than use this offset


[[thrusters]]
name = "fore_port"
type = "T200"
pos = [0.3682922, -0.202912, -0.0352978]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "port"
type = "T200"
pos = [0.062654, -0.3188122, -0.036898]
heading_pitch = [0.0, 0.0]
reversed = true

[[thrusters]]
name = "aft_port"
type = "T200"
pos = [-0.2178734, -0.2152564, -0.0352978]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "sway_aft"
type = "T200"
pos = [-0.3055542, 0.001685, -0.0289478]
heading_pitch = [90.0, 0.0]
reversed = false

[[thrusters]]
name = "aft_starboard"
type = "T200"
pos = [-0.2178734, 0.2186264, -0.0352978]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "starboard"
type = "T200"
pos = [0.062654, 0.3221822, -0.036898]
heading_pitch = [0.0, 0.0]
reversed = false

[[thrusters]]
name = "fore_starboard"
type = "T200"
pos = [0.3682922, 0.206282, -0.0352978]
heading_pitch = [0.0, 90.0]
reversed = false

[[thrusters]]
name = "sway_fore"
type = "T200"
pos = [0.5155614, 0.001685, -0.0289478]
heading_pitch = [90.0, 0.0]
reversed = true


[control_settings]
depth   = { kP = 2.50, kI = 0.03, kD = 4.00, rD = 0.30, ramp_speed = 0.5 }
pitch   = { kP = 0.10, kI = 0.02, kD = 5.00, rD = 30.0 }
heading = { kP = 0.20, kI = 0.004, kD = 1.00, rD = 20.0 }
velx    = { kP = 9.50, kI = 0.12, kD = 0.50, rD = 0.1547 }
vely    = { kP = 10.00, kI = 0.20, kD = 0.50, rD = 0.5 }
roll    = { kP = 0.10, kI = 0.00, kD = 2.00, rD = 30.0 }
quat    = { kP = 30.0, kI = 0.00, kD = 4.00 }


[[drag_planes]]
pos = [0.0, -0.12, 0.0]
normal = [1.0, 0.0, 0.0]
cD = 2.0
area = 0.1


# horizontal, produces drag when diving and pitching
[[uncompensated_drag_planes]]
pos = [0.25, 0.0, 0.0]
normal = [0.0, 0.0, 1.0]
cD = 2.0
area = 0.0


[sensors]
depth = "depth.depth"
dvl_altitude = "dvl.savg_altitude"
depth_offset = "depth.offset_mainsub"
heading_rate = "gx4.ratez"
pitch_rate = "gx4.ratey"
roll_rate = "gx4.ratex"
quaternion = "gx4"

velx = "dvl.velocity_x"
vely = "dvl.velocity_y"
velz = "dvl.velocity_z"

[measurement_error]
velSigma = 0.005
depthSigma = 1.0
accSigma = 1000.0

[components]
port_forecam = [0.0, 0.0, 0.0]
starboard_forecam = [0.0, 0.0, 0.0]
downcam = [0.0, 0.0, 0.0]
sonar = [0.0, 0.0, 0.0]


[cameras.forward]
type = "ueye"
id = 1
camera_name = "ueye_forward_odysseus" # for configuration
width = 640
height = 512
position = [0.48, 0.15, -0.08]
orientation_hpr = [0.0, 0.0, 0.0]

# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [7.2, 5.4]
# The focal length of the LENS in mm
focal_length_mm = 3.6

[cameras.downward]
type = "ueye"
id = 2
camera_name = "ueye_downward_odysseus" # for configuration
width = 1600
height = 1200
rotate180 = true
rotate90 = false
position = [0.0, 0.0, 0.15]
orientation_hpr = [0.0, -90.0, 0.0]

# The optical sensor size of the CAMERA, width and height in mm
# This should typically be in the same ratio as the resolution, above.
sensor_size_wh_mm = [4.76, 3.57]
focal_length_mm = 3.5


[vision_modules.gate]
capture_sources = ["forward"]

[vision_modules.vampire]
capture_sources = ["downward"]

[vision_modules.crucifix]
capture_sources = ["downward"]

[vision_modules.record]
capture_sources = ["forward", "downward"]

[vision_modules.poster]
capture_sources = ["forward", "downward"]

[vision_modules.calibrate]
capture_sources = ["default"]


[actuators]
bottom_torpedo = 8
top_torpedo = 4
manipulator_grab = 9
manipulator_release = 2
